#!/bin/bash

SCRIPT_DIR=$(dirname $0)

PACKAGES="chimp codeceptjs intern testcafe nemo nightmare webdriverio nightwatch wd protractor selenium-webdriver"

rm -rf $SCRIPT_DIR/data $SCRIPT_DIR/jscache
echo '{
    "charts": [
        {
            "chart_id": "npm_downloads",
            "chart_title": "npm downloads",
            "chart_series": [
' > config.pyon
for PACKAGE in $PACKAGES; do
echo '                { "metric": "npm_downloads", "target": "'$PACKAGE'" },' >> config.pyon
done
echo '            ],
        },
    ],
    "metrics": {
        "npm_downloads": {
            "cmd": "",
            "title": "monthly downloads for npm package %(target)s",
        },
    }
}
' >> config.pyon

for PACKAGE in $PACKAGES; do
  npm-download-stats $PACKAGE > /tmp/$PACKAGE-daily.json
  ./convert-daily-json-to-monthly-csv /tmp/$PACKAGE-daily.json > /tmp/$PACKAGE-monthly.csv
  ./command-metrics/src/refresh-measurements import npm_downloads --target $PACKAGE /tmp/$PACKAGE-monthly.csv
done
