#!/bin/bash

SCRIPT_DIR=$(dirname $0)

PACKAGES="nightwatch protractor zombie chimp codeceptjs webdriverio casperjs intern testcafe nightmare selenium-webdriver"

echo rm -rf $SCRIPT_DIR/data $SCRIPT_DIR/jscache
echo '{
    "charts": [
        {
            "chart_id": "npm_weekly_downloads",
            "chart_title": "npm weekly downloads",
            "chart_series": [
' > config.pyon
for PACKAGE in $PACKAGES; do
echo '                { "metric": "npm_weekly_downloads", "target": "'$PACKAGE'", "color": "'$(color-hash $PACKAGE)'" },' >> config.pyon
done
echo '            ],
        },
    ],
    "metrics": {
        "npm_weekly_downloads": {
            "cmd": "npm-download-stats-for-week %(target)s $(date +%%Y-%%m-%%d)",
            "title": "weekly downloads for npm package %(target)s",
        },
    }
}
' >> config.pyon

./command-metrics/src/refresh-measurements measure
./command-metrics/src/refresh-measurements measure

for PACKAGE in $PACKAGES; do
  npm-download-stats $PACKAGE > /tmp/$PACKAGE-daily.json
  ./convert-daily-json-to-weekly-csv /tmp/$PACKAGE-daily.json > /tmp/$PACKAGE-weekly.csv
  ./command-metrics/src/refresh-measurements import npm_weekly_downloads --target $PACKAGE /tmp/$PACKAGE-weekly.csv
done
