#!/usr/bin/env python

import sys
import json
from RFAPI import RFAPI

entity_id = sys.argv[1]

q = {
  "entity": {
    "id": "%s" % entity_id,
    "limit": 1
  }
}

print json.dumps(RFAPI().query(q))
